# Server
server:
  port: 8085

# Spring Devtools
spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  thymeleaf:
    cache: false

  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: scott
    password: rotoakfn33@
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
# sysout으로 출력되는 구문. 운영환경에서는 이렇게 하면 안 됨       show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
